name: 'Setup Android SDK Tools'
author: 'Android-Actions'
description: 'Setup the Android SDK Tools and add them to the path'

runs:
  using: 'composite'
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: 12
    - run: sudo node dist/index.js
      shell: bash
    

branding:
  icon: 'list'
  color: 'green'
